export const ROUTES = {
  HOME: '/',
  AUTH: '/auth',
  DASHBOARD: '/dashboard',
  DOST: '/dost',
  CALENDAR: '/calendar',
  TASKS: '/tasks',
  HABITS: '/habits',
  JOURNAL: '/journal',
  SETTINGS: '/settings',
  BLEND: '/blend',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  PROMO_VIDEO: '/promo-video',
};
