-- Enable the pgvector extension to work with embeddings
create extension if not exists vector;

-- 1. Create the Journal Table
create table journal_entries (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Links to your auth user
  content text not null,
  mood_score int,        -- 1-10 scale
  embedding vector(768), -- Dimensions for Gemini Text Embedding model
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the Vector Search Function (RPC)
-- This allows our Python API to find similar journal entries
create or replace function match_journal_entries (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  mood_score int,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    journal_entries.id,
    journal_entries.content,
    journal_entries.mood_score,
    1 - (journal_entries.embedding <=> query_embedding) as similarity
  from journal_entries
  where 1 - (journal_entries.embedding <=> query_embedding) > match_threshold
  order by journal_entries.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- 3. Create a Tasks Table (Optional, for the "Action" feature)
create table tasks (
  id bigint generated by default as identity primary key,
  user_id text not null,
  title text not null,
  status text default 'todo', -- todo, in-progress, done
  priority text default 'medium',
  created_at timestamp with time zone default timezone('utc'::text, now())
);
